name: Windows Build
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}\Fly\vcpkg_installed
          key: cache
          restore-keys: |
            cache

      - name: Build solution
        working-directory: ${{ github.workspace }}
        run: |
          msbuild Fly.sln `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:VcpkgTriplet=x64-windows `
            /p:OutDir=bin\release\ `
            /p:WindowsTargetPlatformVersion=10.0 `
            /p:RuntimeLibrary=MultiThreaded

      - name: Zip release folder
        run: |
          Compress-Archive -Path "${{ github.workspace }}\Fly\bin\release\*" -DestinationPath "${{ github.workspace }}\Fly\bin\Fly-windows.zip" -Force

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release"
          make_latest: true
          token: ${{ secrets.TOKEN }}
          files: ${{ github.workspace }}\Fly\bin\Fly-windows.zip
