name: Windows Build
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.0.0)'
        required: false
        default: ''
        type: string

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            x64/Release
            x64/Debug
          key: build-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**/*.vcxproj', '**/*.sln') }}
          restore-keys: |
            build-${{ runner.os }}-
            build-

      - name: Build solution
        working-directory: ${{ github.workspace }}
        run: |
          msbuild Fly.sln `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:VcpkgTriplet=x64-windows `
            /p:OutDir=bin\release\ `
            /p:WindowsTargetPlatformVersion=10.0 `
            /p:RuntimeLibrary=MultiThreaded

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fly-windows
          path: ${{ github.workspace }}\Fly\bin\release
          if-no-files-found: error

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: Fly-windows.zip
          draft: false
          prerelease: false
          generate_release_notes: true
