name: Windows Build
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.0.0)'
        required: false
        default: ''
        type: string

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      # Cache vcpkg installed libraries
      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            vcpkg/installed
            vcpkg/buildtrees
            vcpkg/packages
          key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-
            vcpkg-

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install

      # Cache MSBuild intermediate outputs (optional, can be unstable if toolset changes)
      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            x64/Release
            x64/Debug
          key: build-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**/*.vcxproj', '**/*.sln') }}
          restore-keys: |
            build-${{ runner.os }}-
            build-

      - name: Build solution
        run: |
          msbuild Fly.sln `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:VcpkgTriplet=x64-windows `
            /p:WindowsTargetPlatformVersion=10.0 `
            /p:RuntimeLibrary=MultiThreaded

      - name: Find and copy build outputs
        shell: pwsh
        run: |
          mkdir release
          # Find all exe and dll files, excluding the release folder itself
          Get-ChildItem -Recurse -Include *.exe,*.dll -File |
            Where-Object { $_.FullName -notlike "*\release\*" } |
            ForEach-Object { Copy-Item $_.FullName release }

          # Copy assets if they exist
          if (Test-Path assets\*.ttf) { Copy-Item assets\*.ttf release }

          # Create the zip
          Compress-Archive -Path release\* -DestinationPath Fly-windows.zip


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fly-windows
          path: Fly-windows.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: Fly-windows.zip
          draft: false
          prerelease: false
          generate_release_notes: true
